### ISSUE TITLE
Services Section

### ISSUE THREAD

**Issue by stephenajulu** [radity/raditian-free-hugo-theme#12]
Hi, how are you?
Could you kindly add a services section.
Or could you show me how i can do that.
I am a freelancer and this them is great. 
Only missing a services section where people can know what i do.

**Comment by alibabayev** [comment]
Currently we cannot provide services section

**Comment by AntoineSoetewey** [comment]
Hello, is this something you could consider now ? It’s a great theme but for my personal use I feel it is missing a service section.

Thanks again for the theme!

**Comment by AntoineSoetewey** [comment]
> Hello, is this something you could consider now ? It’s a great theme but for my personal use I feel it is missing a service section.
> 
> Thanks again for the theme!

For those who are interested to implement a service section, here is an example that may help: https://datanalyze.be/#services

Code can be found in the repo: https://github.com/AntoineSoetewey/datanalyze
