### ISSUE TITLE
how to run this on forestry.io

### ISSUE THREAD

**Issue by goldcoders** [radity/raditian-free-hugo-theme#2]
HI im having trouble on using it with forestry.io
ive tried some hugo themes , where i can directly use it
and use forestry.io to act like a GUI web interface for the pages/post

have u ever tried using it on forestry.io? and link to netlify?

**Comment by oaksakal** [comment]
we have not used the theme with forestry.io before. Themes you have tried were perhaps tailored for that? (which one?)

**Comment by goldcoders** [comment]
https://github.com/themefisher/northendlab-hugo

i tried this and can easily be used on forestry.io

**Comment by oaksakal** [comment]
thanks @goldcoders
