### ISSUE TITLE
Feature request: favicon

### ISSUE THREAD

**Issue by AntoineSoetewey** [radity/raditian-free-hugo-theme#27]
It’s not a bug, but rather a feature request: how could I add a favicon?

thanks in advance for your help!

**Comment by FedericoNembrini** [comment]
Very late reply, I think you have already solved it.
However, to add a favicon, simply add it to the "static" folder.

**Comment by AntoineSoetewey** [comment]
Thanks for your reply @FedericoNembrini 

I have not solved it, unfortunately. As you can see, I added a favicon in the static folder : https://github.com/AntoineSoetewey/datanalyze/tree/main/static
but it doesn't show up.

Do I have to link it in some way? Any suggestion?

**Comment by FedericoNembrini** [comment]
Is your website https://datanalyze.be/?
From what I can see at the moment the icon is displayed. Also by going to the network requests the image that is loaded is "favicon.ico".
![image](https://user-images.githubusercontent.com/25205086/164739409-df244818-3f46-4503-b1bb-1ba2bd12dbde.png)
![image](https://user-images.githubusercontent.com/25205086/164739431-5837b7a2-cbde-462e-8cfc-a18ea501c733.png)

**Comment by AntoineSoetewey** [comment]
Great thank you !
