### ISSUE TITLE
How to Use Newsletter Form?

### ISSUE THREAD

**Issue by goldcoders** [radity/raditian-free-hugo-theme#3]
I manage to Implement Contact form with Google Form...

But Im Confused with Newsletter, I wanna use mailchimp

how do I manage to use mailchimp on the newsletter,

I see the homepage.yml has the options for newsletter but currently i cannot find a way to subscribe to a mailchimp client

**Comment by oaksakal** [comment]
we have not coded the integration bit. It is up to you to integrate with your preferred newsletter platform. https://mailchimp.com/help/add-a-signup-form-to-your-website/ gives you a good starting point to add the code.

**Comment by goldcoders** [comment]
ive manually edited the html for newsletter and added necessary html mark up and javascript for mailchimp...  thanks
