### ISSUE TITLE
Steps to run the website on local server

### ISSUE THREAD

**Issue by shoebaamir7** [radity/raditian-free-hugo-theme#7]
Please write steps to run the website on local server

**Comment by boazhoch** [comment]
Would love to see 'how to' steps, because I have installed the theme, but i'm getting errors.

**Comment by muc-martin** [comment]
Same for me, I get the following errors:

`Building sites … WARN 2020/07/15 21:56:28 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/07/15 21:56:28 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination`

**Comment by selmanceker** [comment]
Installation steps have been added to the readme. 

Thanks for the feedback.
